name: .NET

on:
  push:
    branches: 
      - develop
      - main
  pull_request:
    branches: 
      - develop
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: cd ./webApi && dotnet restore
    - name: Build
      run: cd ./webApi && dotnet build --no-restore
    - name: Test
      run: cd ./webApi && dotnet test --no-build --verbosity normal
